// The paired sign-flip permutation test. The confirmatory test in this project.
//
// THE UNIT OF ANALYSIS IS THE CASE, NOT THE REPLICATE, and that choice does more work than the test
// itself. Cases differ enormously in difficulty: in this corpus some return the same token on every
// draw and some are genuinely ambiguous. Pooling replicates across cases would let that variation
// dominate, and a test that spends its power on the fact that case 3 is harder than case 7 has none
// left for the question anyone asked. Pairing removes case difficulty entirely, because each case
// is compared only against itself.
//
// THE STATISTIC is the mean over cases of the per-case difference in rate. The null is that those
// differences are symmetric about zero, and the permutation distribution is generated by flipping
// their signs, which is exactly the symmetry the null asserts.
//
// THE ASSUMPTION, STATED. Under no drift, the sign of each per-case difference is exchangeable.
// That holds when the two arms have the SAME number of replicates, because then the two rate
// estimates have the same sampling variance and their difference is symmetric about zero. When the
// arms differ in size the difference is still centred on zero but the per-case variances differ,
// and the test becomes approximate. `exchangeable` records which case it was in and every report
// prints it, because an approximate test presented as exact is the kind of thing that is only
// discovered by whoever is arguing with the result.
//
// WHY NOT A t-TEST. There is no defensible normality assumption over k bounded proportions, several
// of which sit exactly at 0 or 1. In the pilot on this machine two constrained cases returned 8/8
// identical answers, so their per-case rate was exactly 1 with exactly zero observed variance. A
// t-test on a sample containing those is not conservative, it is undefined.
//
// EXACT WHERE POSSIBLE. With k cases there are 2^k sign assignments, and up to k = 20 they are all
// enumerated, so the p-value is exact rather than estimated. Above that the null is sampled with a
// seeded generator and the count includes the observed assignment, which is the standard
// (count + 1) / (draws + 1) correction. Omitting it lets a p-value of zero be reported, and a
// p-value of zero from a sampled null is a statement no sample can support.

import type { Rng } from "./rng.js";

export type PermutationMethod = "exact" | "monte-carlo";

export interface PermutationResult {
  /** Mean over cases of the candidate-minus-baseline difference. The effect, in the metric's units. */
  readonly observed: number;
  readonly p: number;
  readonly method: PermutationMethod;
  /** How many sign assignments were considered. */
  readonly assignments: number;
  /** Number of cases, which is the sample size of this test. */
  readonly k: number;
  /** False when the arms had different replicate counts, making the test approximate. */
  readonly exchangeable: boolean;
}

/** Above this many cases the null is sampled rather than enumerated. 2^20 is about a million. */
export const MAX_EXACT_K = 20;

export interface SignFlipOptions {
  readonly rng?: Rng;
  readonly draws?: number;
  /** Force sampling even when enumeration is possible. Used by the power simulator for speed. */
  readonly forceMonteCarlo?: boolean;
  /** Set false when the two arms had different replicate counts. */
  readonly exchangeable?: boolean;
}

export function signFlipTest(
  deltas: readonly number[],
  options: SignFlipOptions = {},
): PermutationResult {
  const k = deltas.length;
  const exchangeable = options.exchangeable ?? true;
  if (k === 0) {
    return { observed: Number.NaN, p: 1, method: "exact", assignments: 0, k: 0, exchangeable };
  }

  const observed = deltas.reduce((a, b) => a + b, 0) / k;
  const target = Math.abs(observed);

  // A suite where nothing moved at all. Every sign assignment gives exactly zero, so every one is
  // at least as extreme as the observed zero and p is exactly 1. Worth handling explicitly because
  // it is the common case for a healthy canary and because floating point comparison against zero
  // is where an off-by-one in the tail count would hide.
  if (deltas.every((d) => d === 0)) {
    return { observed: 0, p: 1, method: "exact", assignments: 1, k, exchangeable };
  }

  const useExact = k <= MAX_EXACT_K && options.forceMonteCarlo !== true;
  const tol = 1e-12;

  if (useExact) {
    const total = 2 ** k;
    let atLeastAsExtreme = 0;
    for (let mask = 0; mask < total; mask += 1) {
      let sum = 0;
      for (let i = 0; i < k; i += 1) {
        sum += (mask >> i) & 1 ? -(deltas[i] as number) : (deltas[i] as number);
      }
      if (Math.abs(sum / k) >= target - tol) atLeastAsExtreme += 1;
    }
    return {
      observed,
      p: atLeastAsExtreme / total,
      method: "exact",
      assignments: total,
      k,
      exchangeable,
    };
  }

  const rng = options.rng;
  if (rng === undefined) {
    throw new Error(
      "a sampled permutation test needs a seeded rng; Math.random is not allowed here",
    );
  }
  const draws = options.draws ?? 20_000;
  let atLeastAsExtreme = 0;
  for (let d = 0; d < draws; d += 1) {
    let sum = 0;
    for (let i = 0; i < k; i += 1) {
      sum += rng() < 0.5 ? -(deltas[i] as number) : (deltas[i] as number);
    }
    if (Math.abs(sum / k) >= target - tol) atLeastAsExtreme += 1;
  }
  return {
    observed,
    // The observed assignment is one of the possible ones, so it is counted on both sides.
    p: (atLeastAsExtreme + 1) / (draws + 1),
    method: "monte-carlo",
    assignments: draws,
    k,
    exchangeable,
  };
}
