// Numbers in prose, regenerated from the artifacts they describe.
//
// A hand-maintained number is a claim that was true once, and the one that goes stale is always the
// one somebody quotes. This project already had four of them: a README that said "24 cases" after
// the corpus grew, a test count that moved every time a package gained a file, a freeze status
// duplicated in three documents, and a calibration summary that could only be refreshed by someone
// remembering to.
//
// So every such number lives between markers and is written by this script:
//
//     <!-- GENERATED:name -->   ... regenerated content ...   <!-- /GENERATED -->
//
// `--check` exits 1 when any block is stale, which is what makes the guarantee enforceable rather
// than aspirational. It is wired into CI and into `pnpm audit:release`.
//
// WHAT THIS DOES NOT COVER. Numbers in ordinary prose outside a block are still hand-typed and still
// go stale. The honest scope is: anything a script can derive belongs in a block, and anything that
// needs a sentence around it is a judgement that a human owns. `docs/CORPUS.md` carries its own
// block written by `case-composition.mjs`, which is left alone here rather than absorbed, because a
// composition table is a different derivation with a different owner.
//
// Usage: node scripts/generated-blocks.mjs [--check]

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(fileURLToPath(new URL("..", import.meta.url)));
const CHECK = process.argv.includes("--check");

const read = (p) => readFileSync(join(ROOT, p), "utf8");
const readJson = (p) => JSON.parse(read(p));
const has = (p) => existsSync(join(ROOT, p));

// ---- the generators -------------------------------------------------------------------------------

/** Freeze status, from the freeze records themselves rather than from anybody's memory of them. */
function freezeStatus() {
  const rows = [];
  for (const split of readdirSync(join(ROOT, "corpus")).sort()) {
    const p = `corpus/${split}/FREEZE.json`;
    if (!has(p)) continue;
    const f = readJson(p);
    rows.push(
      `| \`${split}\` | ${f.caseCount} | ${f.frozenAt} | **${f.state}** | ${f.frozenAtCommit === null ? "none recorded" : `\`${String(f.frozenAtCommit).slice(0, 12)}\``} |`,
    );
  }
  const anyCashed = rows.some((r) => r.includes("**cashed**"));
  return [
    "| split | cases | frozen | ordering proof | commit |",
    "|---|---|---|---|---|",
    ...rows,
    "",
    anyCashed
      ? "At least one split records a cashed ordering proof. `pnpm verify:freeze` should now exit 0 for it."
      : "**No split has a cashed ordering proof, and `pnpm verify:freeze` exits 1 by design.** The corpus could not be committed before the detector existed in the environment that produced this repository, so the state is UNAVAILABLE rather than pending. That is a claim about what is obtainable here, not about work still to do.",
  ].join("\n");
}

/** Detector calibration, from results/calibration.json. Absent is reported as absent. */
function calibrationSummary() {
  if (!has("results/calibration.json")) {
    return "No calibration has been run in this checkout. `node scripts/calibrate.mjs` produces it, makes no provider call, and is reproducible from a seed.";
  }
  const c = readJson("results/calibration.json");
  const pct = (x) => `${(x * 100).toFixed(1)}%`;
  const power = (c.powerCurve ?? []).find((p) => p.power >= 0.8);
  return [
    "| quantity | measured |",
    "|---|---|",
    `| corpus | \`${String(c.corpusDigest).slice(0, 16)}\`, ${c.cases} cases, ${c.replicates} replicates |`,
    `| A/A false positives | **${c.aa.drift} of ${c.aa.total}** = ${pct(c.aa.falsePositiveRate)} against a nominal 5.0% |`,
    `| live baseline vs candidate arm | \`${c.aa.liveVerdict}\` |`,
    `| first grid point at or above 80% power | ${power === undefined ? "not reached on the grid" : `${(power.achievedDrop * 100).toFixed(1)} points`} |`,
    `| predicted MDE | ${c.mde.predicted === null ? "not reached on the grid" : `${(c.mde.predicted * 100).toFixed(1)} points`} |`,
    `| prediction agrees with measurement | ${c.mde.agrees ? "yes" : "**NO**"} |`,
    `| rule of three at n=${c.replicates} | an all-passing case still permits a ${pct(c.mde.allPassCeiling)} failure rate |`,
    "",
    "Regenerated by `node scripts/calibrate.mjs`. Seeded, makes no provider call, exact on re-run.",
  ].join("\n");
}

/** The watcher protocol, summarised from the thresholds the code actually uses. */
function watcherProtocol() {
  const src = read("packages/detect/src/eprocess.ts");
  const healthy = /HEALTHY_MULTIPLE = (\d+)/.exec(src)?.[1] ?? "?";
  const threshold = /rebaselineEvidenceMultiple: (\d+)/.exec(src)?.[1] ?? "?";
  return [
    "| state | evidence multiple | what it means | action |",
    "|---|---|---|---|",
    `| \`healthy\` | under ${healthy}x | about as sensitive as a fresh watch | none |`,
    `| \`degraded\` | ${healthy}x to ${threshold}x | measurably slower to notice a real regression | plan a rotation |`,
    `| \`blind\` | ${threshold}x and above | a regression takes multiples longer to surface than anyone expects | \`sentinel baseline rotate\` |`,
    "",
    "`sentinel watch --status` reports the multiple, the ticks in this generation, the ticks across",
    "every generation, and the recommended action. **Spending sensitivity is never a regression and",
    "never sets a non-zero exit code.**",
  ].join("\n");
}

/** Remaining risks, derived from what is on disk rather than from a list somebody maintains. */
function remainingRisks() {
  const rows = [];
  const registry = read("packages/run/src/providers/index.ts");
  const unrun = [
    ...registry.matchAll(
      /id: "([a-z_]+)",\s*\n\s*credential: "([^"]+)",\s*\n\s*everRun: (true|false)/g,
    ),
  ]
    .filter((m) => m[3] === "false")
    .map((m) => m[1]);
  if (unrun.length > 0) {
    rows.push(
      `| BYOK adapters shipped and **unrun** | ${unrun.map((u) => `\`${u}\``).join(", ")} | OPEN. No credential exists in this environment; they are exercised against a fake transport only. |`,
    );
  }
  const anyCashed = readdirSync(join(ROOT, "corpus"))
    .filter((d) => has(`corpus/${d}/FREEZE.json`))
    .some((d) => readJson(`corpus/${d}/FREEZE.json`).state === "cashed");
  rows.push(
    `| Corpus ordering proof | \`verify:freeze\` | ${anyCashed ? "PARTIALLY CLOSED." : "OPEN. UNAVAILABLE in this environment, and stated as such rather than as pending."} |`,
  );
  rows.push(
    "| No real provider drift observed | the whole project | **OPEN, and the largest gap.** Every positive result is an injected perturbation or a deliberate model swap. The false-positive rate is measured; the true-positive rate in the wild is not. |",
  );
  rows.push(
    "| Watcher goes blind on a quiet stream | `evidenceMultiple` | MITIGATED, not fixed. It is a trade-off rather than a defect, is reported, and has a rotation protocol. |",
  );
  return ["| risk | where | status |", "|---|---|---|", ...rows].join("\n");
}

const BLOCKS = {
  "freeze-status": freezeStatus,
  "calibration-summary": calibrationSummary,
  "watcher-protocol": watcherProtocol,
  "remaining-risks": remainingRisks,
};

// ---- the rewriter ---------------------------------------------------------------------------------

const TARGETS = [
  "README.md",
  "RESULTS.md",
  "docs/DETECTOR_CARD.md",
  "docs/WATCHER.md",
  "docs/FREEZE.md",
];

let stale = 0;
let written = 0;
let found = 0;

for (const target of TARGETS) {
  if (!has(target)) continue;
  const before = read(target);
  let after = before;

  for (const [name, generate] of Object.entries(BLOCKS)) {
    const open = `<!-- GENERATED:${name} -->`;
    const close = "<!-- /GENERATED -->";
    const start = after.indexOf(open);
    if (start === -1) continue;
    const end = after.indexOf(close, start);
    if (end === -1) {
      console.error(`  UNCLOSED  ${target} has ${open} with no ${close}`);
      stale += 1;
      continue;
    }
    found += 1;
    const body = `${open}\n${generate()}\n`;
    after = after.slice(0, start) + body + after.slice(end);
  }

  if (after === before) continue;
  stale += 1;
  if (CHECK) {
    console.error(`  STALE     ${target}`);
    continue;
  }
  writeFileSync(join(ROOT, target), after);
  written += 1;
  console.log(`  written   ${target}`);
}

if (found === 0) {
  console.error(
    "no GENERATED blocks found. Either the markers were removed or the target list is wrong.",
  );
  process.exitCode = 1;
} else if (CHECK && stale > 0) {
  console.error("");
  console.error(`${stale} block(s) are out of date with the artifacts they describe.`);
  console.error(
    "Run `pnpm blocks:write`. If the underlying artifact is what changed, say so in RESULTS.md.",
  );
  process.exitCode = 1;
} else if (CHECK) {
  console.log(`all ${found} GENERATED block(s) are current`);
} else {
  console.log(`${found} block(s) checked, ${written} file(s) written`);
}
